server:
  port: 8888

  logging:
    path: logs
    file: mylog.log
    logging.level.com.course.controller: debug

spring:
  application:
      name: course
  dataSource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: root

mybatis:
  config-location:
   - mybatis-config.xml
  mapper-locations:
    - mapper/*
  type-aliases-package: com.course