server:
  port: 8888

logging:
  path: logs
  file: myLog.log

spring:
  application:
       name: course1

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course
    username: root
    password: root

mybatis:
  mybatis-locations:
    - mybatis-config.xml
  mapper-locations:
    - mapper/*.xml
  type-aliases-package: com.course